Removed earliest call to renaming function.
Bug report was:

By Kris Maglione, comments:
This version didn't pass full review because of the following issues:

I get the following error in the Error Console at startup:

Error: NS_ERROR_ILLEGAL_VALUE: 'Illegal value' when calling method:
[nsISessionStore::getWindowValue]
Source file: chrome://firetitle/content/firetitle.js
Line: 127

You need to correct them to get full approval. Thanks.

Tested on Linux with Firefox